base_score: null
booster: null
callbacks: null
colsample_bylevel: null
colsample_bynode: null
colsample_bytree: 0
device: null
early_stopping_rounds: null
enable_categorical: false
eval_metric: null
feature_types: null
features: '[''City'', ''PaymentTier'', ''Age'', ''EverBenched'', ''ExperienceInCurrentDomain'']'
gamma: 7.578588035809309
grow_policy: null
importance_type: null
interaction_constraints: null
learning_rate: null
max_bin: null
max_cat_threshold: null
max_cat_to_onehot: null
max_delta_step: null
max_depth: 15
max_leaves: null
min_child_weight: 6
missing: .nan
model_class: XGBClassifier
monotone_constraints: null
multi_strategy: null
n_estimators: 180
n_jobs: null
num_parallel_tree: null
objective: binary:logistic
random_state: null
reg_alpha: 124
reg_lambda: null
sampling_method: null
scale_pos_weight: null
subsample: null
tree_method: null
use_label_encoder: false
validate_parameters: null
verbosity: null
